import os

BOT_TOKEN = os.getenv("BOT_TOKEN")

ASAAS_API_KEY = os.getenv("ASAAS_API_KEY")
ASAAS_WEBHOOK_TOKEN = os.getenv("ASAAS_WEBHOOK_TOKEN")

DATABASE_URL = os.getenv("DATABASE_URL")

ADMINS = [8276989322]
SUPORTE_CHAT = 8276989322

BOT_NAME = "RC_STORE"
